export enum ExchangerType {
  VELODROME = 'Velodrome',
  AERODROME = 'Aerodrome',
  BEEFY = 'Beefy',
  CONVEX = 'Convex',
  DYSON = 'Dyson',
  VEPLUS = 'Veplus',
  VELOCORE = 'Velocore',
  SOLUNEA = 'Solunea',
  CHRONOS = 'Chronos',
  VESYNC = 'Vesync',
  GND = 'Gnd',
  DRACULA = 'Dracula',
  MAVERICK = 'Maverick',
  CURVE = 'Curve',
  BASESWAP = 'Baseswap',
  BALANCER = 'Balancer',
  PANCAKE = 'Pancake',
  SYNCSWAP = 'Syncswap',
  LYNEX = 'Lynex',
  FRAX = 'Frax Finance',
  SWAPBLAST = 'Swapblast',
  SWAPBASED = 'Swapbased',
  THRUSTER = 'Thruster',
}

export const DEX_SUPPORT_SKIM: ExchangerType[] = [
  ExchangerType.VELODROME,
  ExchangerType.AERODROME,
  ExchangerType.VELOCORE,
  ExchangerType.SOLUNEA,
];
