export enum ExchangerType {
  VELODROME = 'Velodrome',
  AERODROME = 'Aerodrome',
  BEEFY = 'Beefy',
  CONVEX = 'Convex',
  VEPLUS = 'Veplus',
  VELOCORE = 'Velocore',
  CHRONOS = 'Chronos',
  VESYNC = 'Vesync',
  GND = 'Gnd',
  DRACULA = 'Dracula',
  MAVERICK = 'Maverick',
  CURVE = 'Curve',
  PANCAKE = 'Pancake',
  SYNCSWAP = 'Syncswap',
  LYNEX = 'Lynex',
  FRAX = 'Frax Finance',
  SWAPBLAST = 'Swapblast',
  SWAPBASED = 'Swapbased',
  THRUSTER = 'Thruster',
  AMBIENT = 'Ambient',
  BLADESWAP = 'Bladeswap',
  TRADERJOE = 'Traderjoe',
}

export const DEX_SUPPORT_SKIM: ExchangerType[] = [
  ExchangerType.VELODROME,
  ExchangerType.AERODROME,
  ExchangerType.VELOCORE,
];
