name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Build Docker image
        run: |
          docker build . -t cr.yandex/crp6lhbprjft0c8fhg61/overnight/dex-aggregator:1 --platform linux/amd64 && \
          docker login --username oauth --password ${{ secrets.CR_TOKEN }} cr.yandex && \
          docker push cr.yandex/crp6lhbprjft0c8fhg61/overnight/dex-aggregator:1

      - name: SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker login --username oauth --password ${{ secrets.CR_TOKEN }} cr.yandex && \
            docker pull cr.yandex/crp6lhbprjft0c8fhg61/overnight/dex-aggregator:1 && \
            docker-compose -f /home/ubuntu/front/docker-compose.yaml up -d --no-deps dex-aggregator
